import { RuleTester } from "eslint";
import tsParser from "@typescript-eslint/parser";
import { describe, it } from "vitest";
import rule from "./engine-purity.js";

RuleTester.describe = describe;
RuleTester.it = it;

const ruleTester = new RuleTester({
  languageOptions: { parser: tsParser, ecmaVersion: 2022, sourceType: "module" },
});

ruleTester.run("engine-purity", rule, {
  valid: [
    { name: "module constants", code: `export const LIMIT = 10; const KINDS = ["a", "b"] as const;` },
    { name: "local mutable state", code: `export function f() { let total = 0; const seen = new Map(); seen.set("a", 1); total += 1; return total; }` },
    { name: "mutating a parameter that shadows nothing", code: `export function f(state: { list: number[] }) { state.list.push(1); }` },
    { name: "a shadowing local with a module name", code: `const items = [1]; export function f() { const items: number[] = []; items.push(2); return items; }` },
    { name: "reading a module constant", code: `const TABLE = [1, 2]; export function f() { return TABLE.map((x) => x * 2); }` },
    { name: "deterministic Math members", code: `export const f = (x: number) => Math.floor(Math.max(0, Math.imul(x, 3)));` },
    { name: "deterministic Math members by string key", code: `export const f = (x: number) => Math["floor"](x) + globalThis.Math.abs(x);` },
    { name: "a deterministic Math member destructured", code: `const { floor, max } = Math; export const f = (x: number) => floor(max(x, 0));` },
    { name: "an aliased Math used deterministically", code: `const M = Math; export const f = (x: number) => M.floor(x);` },
    { name: "a local Math shadowing the global", code: `export function f() { const Math = { random: () => 4 }; return Math.random(); }` },
    { name: "a module Math shadowing the global", code: `const Math = { random: () => 4 }; export const f = () => Math.random();` },
    { name: "a parameter named Date", code: `export function f(Date: { now(): number }) { return Date.now(); }` },
    { name: "a local crypto shadowing the global", code: `export function f(crypto: { randomUUID(): string }) { return crypto.randomUUID(); }` },
    { name: "Date as a type", code: `export function f(when: Date): number { return 1; }` },
    { name: "readonly static constant", code: `export class Rules { static readonly LIMIT = 10; }` },
    { name: "instance fields", code: `export class Counter { count = 0; bump() { this.count += 1; } }` },
    { name: "a class declared per call", code: `export function f() { class Local { static n = 0; } return Local; }` },
    { name: "mutating a local that shadows an import", code: `import { items } from "./x"; export function f() { const items: number[] = []; items.push(1); return items; }` },
    { name: "writing a local destructured binding", code: `export function f(source: { list: number[] }) { const { list } = source; list.push(1); }` },
  ],
  invalid: [
    { name: "a top-level let", code: `let counter = 0; export const read = () => counter;`, errors: [{ messageId: "mutableBinding" }] },
    { name: "a top-level Map", code: `const cache = new Map<string, number>(); export const read = () => cache.size;`, errors: [{ messageId: "mutableValue" }] },
    { name: "mutating a module array from a function", code: `const seen: number[] = []; export function f() { seen.push(1); }`, errors: [{ messageId: "mutation" }] },
    { name: "assigning into a module object", code: `const state = { n: 0 }; export function f() { state.n = 1; }`, errors: [{ messageId: "mutation" }] },
    { name: "Math.random", code: `export const roll = () => Math.random();`, errors: [{ messageId: "random" }] },
    { name: "Date.now", code: `export const now = () => Date.now();`, errors: [{ messageId: "clock" }] },
    { name: "new Date()", code: `export const now = () => new Date();`, errors: [{ messageId: "clock" }] },
    { name: "performance.now", code: `export const now = () => performance.now();`, errors: [{ messageId: "clock" }] },
    { name: "Math['random']", code: `export const roll = () => Math["random"]();`, errors: [{ messageId: "random" }] },
    { name: "Math[`random`]", code: "export const roll = () => Math[`random`]();", errors: [{ messageId: "random" }] },
    { name: "Math with a computed key", code: `export const pick = (key: "floor") => Math[key](1);`, errors: [{ messageId: "opaque" }] },
    { name: "Math.random?.()", code: `export const roll = () => Math.random?.();`, errors: [{ messageId: "random" }] },
    { name: "globalThis.Math.random", code: `export const roll = () => globalThis.Math.random();`, errors: [{ messageId: "random" }] },
    { name: "window.Math.random", code: `export const roll = () => window.Math.random();`, errors: [{ messageId: "random" }] },
    { name: "globalThis['Math']['random']", code: `export const roll = () => globalThis["Math"]["random"]();`, errors: [{ messageId: "random" }] },
    { name: "self.crypto.randomUUID", code: `export const id = () => self.crypto.randomUUID();`, errors: [{ messageId: "random" }] },
    { name: "crypto.getRandomValues", code: `export const fill = (a: Uint8Array) => crypto.getRandomValues(a);`, errors: [{ messageId: "random" }] },
    { name: "a destructured random", code: `const { random } = Math; export const roll = () => random();`, errors: [{ messageId: "random" }] },
    { name: "a destructured random with a rename and default", code: `export function f() { const { random: r = () => 0 } = Math; return r(); }`, errors: [{ messageId: "random" }] },
    { name: "a destructured random by string key", code: `const { ["random"]: r } = Math; export const roll = () => r();`, errors: [{ messageId: "random" }] },
    { name: "a nested destructure from globalThis", code: `const { Math: { random } } = globalThis; export const roll = () => random();`, errors: [{ messageId: "random" }] },
    { name: "a rest destructure of Math", code: `const { ...all } = Math; export const roll = () => all.random();`, errors: [{ messageId: "opaque" }] },
    { name: "an aliased Math.random", code: `const r = Math.random; export const roll = () => r();`, errors: [{ messageId: "random" }] },
    { name: "an aliased Math", code: `const M = Math; export const roll = () => M.random();`, errors: [{ messageId: "random" }] },
    { name: "an alias of an alias", code: `export function f() { const A = Math; const B = A; return B.random(); }`, errors: [{ messageId: "random" }] },
    { name: "an aliased Math assigned later", code: `export function f() { let M; M = Math; return M.random(); }`, errors: [{ messageId: "random" }] },
    { name: "an aliased globalThis", code: `const g = globalThis; export const roll = () => g.Math.random();`, errors: [{ messageId: "random" }] },
    { name: "a cast Math", code: `export const roll = () => (Math as Math).random();`, errors: [{ messageId: "random" }] },
    { name: "Math passed away", code: `export const roll = () => Reflect.get(Math, "random")();`, errors: [{ messageId: "opaque" }] },
    { name: "new Date via an alias", code: `const D = Date; export const now = () => new D();`, errors: [{ messageId: "clock" }] },
    { name: "globalThis.Date.now", code: `export const now = () => globalThis.Date.now();`, errors: [{ messageId: "clock" }] },
    { name: "a destructured Date", code: `const { Date: Clock } = globalThis; export const now = () => Clock.now();`, errors: [{ messageId: "clock" }] },
    { name: "Date shadowed only in another function", code: `export function f(Date: number) { return Date; } export const now = () => Date.now();`, errors: [{ messageId: "clock" }] },
    { name: "an aliased performance", code: `const p = performance; export const now = () => p.now();`, errors: [{ messageId: "clock" }] },
    { name: "a top-level var", code: `var counter = 0; export const read = () => counter;`, errors: [{ messageId: "mutableBinding" }] },
    { name: "an exported top-level let", code: `export let counter = 0;`, errors: [{ messageId: "mutableBinding" }] },
    { name: "a destructured top-level let", code: `let { a, b } = { a: 1, b: 2 }; export const read = () => a + b;`, errors: [{ messageId: "mutableBinding" }] },
    { name: "mutating a destructured module binding", code: `const { list } = { list: [1] }; export function f() { list.push(2); }`, errors: [{ messageId: "mutation" }] },
    { name: "mutating an array-destructured module binding", code: `const [first] = [[1]]; export function f() { first.push(2); }`, errors: [{ messageId: "mutation" }] },
    { name: "a mutable static field", code: `export class Registry { static count = 0; }`, errors: [{ messageId: "mutableBinding" }] },
    { name: "a readonly static Map", code: `export class Registry { static readonly cache = new Map<string, number>(); }`, errors: [{ messageId: "mutableValue" }] },
    { name: "writing a static field from a function", code: `export class Registry { static readonly limit = 1; } export function f() { (Registry as { limit: number }).limit = 2; }`, errors: [{ messageId: "mutation" }] },
    { name: "mutating an imported binding", code: `import { table } from "./x"; export function f() { table.push(1); }`, errors: [{ messageId: "mutation" }] },
    { name: "a string-keyed mutating call", code: `const seen: number[] = []; export function f() { seen["push"](1); }`, errors: [{ messageId: "mutation" }] },
    { name: "deleting from a module object", code: `const state: Record<string, number> = { n: 0 }; export function f() { delete state.n; }`, errors: [{ messageId: "mutation" }] },
    { name: "destructuring into a module object", code: `const state = { n: 0 }; export function f(source: { n: number }) { ({ n: state.n } = source); }`, errors: [{ messageId: "mutation" }] },
  ],
});
